import Link from 'next/link'
import './globals.css'
import { Inter, Roboto, PT_Sans } from 'next/font/google'
import Header from '@/components/layout/Header'
import Footer from '@/components/layout/Footer'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

type Props = {
  children?: React.ReactNode | React.ReactElement | React.ReactElement[]
}


export default function RootLayout({
  children,
}: Props) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=PT+Sans:ital,wght@0,400;0,700;1,400;1,700&family=Roboto:wght@300;400;500;700&display=swap" rel="stylesheet" />
      </head>
      <body >
        <div className="wrapper">
          <Header />
          <div className="container">
            <main className="main">
              <aside className="sidebar">
                <div className="sidebar__title">
                  <div className="button">
                    Каталог
                  </div>
                </div>
                <div className="sidebar__list">
                  <a href="#" className="sidebar__item">Категория</a>
                  <a href="#" className="sidebar__item">Категория</a>
                  <a href="#" className="sidebar__item">Категория</a>
                  <a href="#" className="sidebar__item">Категория</a>
                  <a href="#" className="sidebar__item">Категория</a>
                  <a href="#" className="sidebar__item">Категория</a>
                </div>
              </aside>
              <div className="content">
                {children}
              </div>
            </main>
          </div>
          <Footer />
        </div>
      </body>
    </html>
  )
}
