import { Header } from '@/components/Header/Header'
import { Footer } from '@/components/Footer/Footer'
import { Aside } from '@/components/Aside/Aside'


import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/scrollbar";
import "swiper/css/grid";

import "../styles/style.scss"
import "../shared/styles/index.scss"

import { Container, Modal, Stack } from '@/shared'
import Providers from '@/redux/provider';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />

        <script src="https://api-maps.yandex.ru/2.1/?lang=ru_RU&amp;apikey=<ваш API-ключ>" type="text/javascript"></script>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin='use-credentials' />
        <link href="https://fonts.googleapis.com/css2?family=PT+Sans:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet" />

        <title>Главная</title>
      </head>

      <body>
        <Providers>
          <Stack flexDirection='column'>
            <Header />
            {children}
          </Stack>
        </Providers>
      </body>

    </html>
  )
}

//  {/* @ts-expect-error Async Server Component*/}
//  <Aside />

//  <div className="content">
//    {children}
//  </div>