import { Header } from '@/components/base/Header'
import { Footer } from '@/components/base/Footer'
import { Aside } from '@/components/base/Aside'

import "../styles/style.scss"

import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/scrollbar";
import "swiper/css/grid";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />

        <script src="https://api-maps.yandex.ru/2.1/?lang=ru_RU&amp;apikey=<ваш API-ключ>" type="text/javascript"></script>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin='use-credentials' />
        <link href="https://fonts.googleapis.com/css2?family=PT+Sans:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet" />

        <title>Главная</title>
      </head>

      <body>
        <div className="wrapper">

          <Header />

          <main className="main">
            <div className="container">

              {/* @ts-expect-error Async Server Component */}
              <Aside />

              <div className="content">
                {children}
              </div>
            </div>
          </main>

          <Footer />

        </div>
      </body>

    </html>
  )
}
